//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServiceReference_01 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://motopoint.com.ar/", ConfigurationName="ServiceReference_01.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numeroTarjeta del espacio de nombres http://motopoint.com.ar/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://motopoint.com.ar/PagoMembresia", ReplyAction="*")]
        BLL.ServiceReference_01.PagoMembresiaResponse PagoMembresia(BLL.ServiceReference_01.PagoMembresiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://motopoint.com.ar/PagoMembresia", ReplyAction="*")]
        System.Threading.Tasks.Task<BLL.ServiceReference_01.PagoMembresiaResponse> PagoMembresiaAsync(BLL.ServiceReference_01.PagoMembresiaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagoMembresiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagoMembresia", Namespace="http://motopoint.com.ar/", Order=0)]
        public BLL.ServiceReference_01.PagoMembresiaRequestBody Body;
        
        public PagoMembresiaRequest() {
        }
        
        public PagoMembresiaRequest(BLL.ServiceReference_01.PagoMembresiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://motopoint.com.ar/")]
    public partial class PagoMembresiaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroSeguridad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaValidez;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombreTitular;
        
        public PagoMembresiaRequestBody() {
        }
        
        public PagoMembresiaRequestBody(string numeroTarjeta, string numeroSeguridad, string fechaValidez, string nombreTitular) {
            this.numeroTarjeta = numeroTarjeta;
            this.numeroSeguridad = numeroSeguridad;
            this.fechaValidez = fechaValidez;
            this.nombreTitular = nombreTitular;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagoMembresiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagoMembresiaResponse", Namespace="http://motopoint.com.ar/", Order=0)]
        public BLL.ServiceReference_01.PagoMembresiaResponseBody Body;
        
        public PagoMembresiaResponse() {
        }
        
        public PagoMembresiaResponse(BLL.ServiceReference_01.PagoMembresiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://motopoint.com.ar/")]
    public partial class PagoMembresiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PagoMembresiaResult;
        
        public PagoMembresiaResponseBody() {
        }
        
        public PagoMembresiaResponseBody(bool PagoMembresiaResult) {
            this.PagoMembresiaResult = PagoMembresiaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BLL.ServiceReference_01.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BLL.ServiceReference_01.ServiceSoap>, BLL.ServiceReference_01.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference_01.PagoMembresiaResponse BLL.ServiceReference_01.ServiceSoap.PagoMembresia(BLL.ServiceReference_01.PagoMembresiaRequest request) {
            return base.Channel.PagoMembresia(request);
        }
        
        public bool PagoMembresia(string numeroTarjeta, string numeroSeguridad, string fechaValidez, string nombreTitular) {
            BLL.ServiceReference_01.PagoMembresiaRequest inValue = new BLL.ServiceReference_01.PagoMembresiaRequest();
            inValue.Body = new BLL.ServiceReference_01.PagoMembresiaRequestBody();
            inValue.Body.numeroTarjeta = numeroTarjeta;
            inValue.Body.numeroSeguridad = numeroSeguridad;
            inValue.Body.fechaValidez = fechaValidez;
            inValue.Body.nombreTitular = nombreTitular;
            BLL.ServiceReference_01.PagoMembresiaResponse retVal = ((BLL.ServiceReference_01.ServiceSoap)(this)).PagoMembresia(inValue);
            return retVal.Body.PagoMembresiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BLL.ServiceReference_01.PagoMembresiaResponse> BLL.ServiceReference_01.ServiceSoap.PagoMembresiaAsync(BLL.ServiceReference_01.PagoMembresiaRequest request) {
            return base.Channel.PagoMembresiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BLL.ServiceReference_01.PagoMembresiaResponse> PagoMembresiaAsync(string numeroTarjeta, string numeroSeguridad, string fechaValidez, string nombreTitular) {
            BLL.ServiceReference_01.PagoMembresiaRequest inValue = new BLL.ServiceReference_01.PagoMembresiaRequest();
            inValue.Body = new BLL.ServiceReference_01.PagoMembresiaRequestBody();
            inValue.Body.numeroTarjeta = numeroTarjeta;
            inValue.Body.numeroSeguridad = numeroSeguridad;
            inValue.Body.fechaValidez = fechaValidez;
            inValue.Body.nombreTitular = nombreTitular;
            return ((BLL.ServiceReference_01.ServiceSoap)(this)).PagoMembresiaAsync(inValue);
        }
    }
}
